# Generated by Django 5.2.12 on 2026-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate (-90 to 90)')),
                ('longitude', models.FloatField(help_text='Longitude coordinate (-180 to 180)')),
                ('pothole_depth', models.FloatField(help_text='Pothole depth measurement (e.g. cm or mm, >= 0)')),
                ('sensor_timestamp', models.DateTimeField(db_index=True, help_text='Timestamp recorded on-device in the field')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Server record insertion timestamp')),
            ],
            options={
                'ordering': ['sensor_timestamp'],
            },
        ),
    ]
